# specify language
language: java
jdk:
- openjdk8
- oraclejdk8
- openjdk11
- oraclejdk11
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn test
after_success:
- bash <(curl -s https://codecov.io/bash)